### PR TITLE
First draft of scope_()

### LINKED ISSUE #28: 'defer' + 'scoped' side effects
The goal is to enable writing, instead of this,

``` R
with_dir(directory, {
    // code
})
```

to write this:

``` R
scoped_dir(directory)
// code
```

This can be accomplished with a couple tools. The main trick is to use `on.exit`, but attach its execution to an arbitrary parent frame. We create a function `defer` that accomplishes that:

``` R
defer <- function(expr, envir = parent.frame()) {

  # Create a call that must be evaluated in the parent frame (as
  # that's where functions and symbols need to be resolved)
  call <- substitute(
    evalq(expr, envir = envir),
    list(expr = substitute(expr), envir = parent.frame())
  )

  # Use 'do.call' with 'on.exit' to attach the evaluation to
  # the exit handlers of the selected frame
  do.call("on.exit", list(substitute(call), add = TRUE), envir = envir)

  # TODO: Not sure what we should actually return.
}
```

And then create functions that provide their 'state' and 'reset' at the exit of that scope:

``` R
scoped_dir <- function(directory) {
    owd <- setwd(directory)
    defer(setwd(owd), parent.frame())
}
```

Any thoughts on whether something like this would be appropriate for `withr`?

---

For completeness, this was inspired by the discussion here: https://stat.ethz.ch/pipermail/r-devel/2013-November/067874.html

### PR DESCRIPTION
**Pull request by krlmlr**
Fixes #28 (eventually).

@jimhester: That was _easy_.

@kevinushey: Thanks for your package. Try, for instance, `scope_(setwd)`. Any plans for CRAN release yet? ;-)

### CODE REVIEW

**Comment by jimhester** [comment]
@krlmlr you will have to explicitly attach devtools to get `Remotes:` to work on travis with CRAN devtools.

**Comment by kevinushey** [comment]
That's awesome! Some definite wizardry going on in the `scope_` definition :smile: 

I'm still waiting a bit to convince myself that the `defer_parent` implementation will work as expected in all contexts; I think I will let it 'bake' for a bit longer and submit after that.

**Comment by krlmlr** [comment]
Thanks. Do you think it's better to add `.scope_env = parent.frame()` to the formals of the generated function, instead of relying on `defer_parent`?

**Comment by kevinushey** [comment]
Sorry, I'm a bit foggy on what you mean -- can you elaborate a bit more?

**Comment by krlmlr** [comment]
Currently:

```
> scope_(setwd)
function (dir) 
{
    old <- setwd(dir = dir)
    later::defer_parent(setwd(old))
    old
}
```

But it could be:

```
> scope_(setwd)
function (dir, .scope_env = parent.frame()) 
{
    old <- setwd(dir = dir)
    later::defer(setwd(old), envir = .scope_env)
    old
}
```

**Comment by jimhester** [comment]
Ended up merging this manually (https://github.com/jimhester/withr/commit/54becef3a01c41e62ed1366c734270b8054beead) and doing the rest of the work to get it all the functions integrated + tests.

It mostly uses this implementation plus @krlmlr's suggestion to use `.scoped_envir`, I also ended up calling the functions `scoped_` as that sounds a little nicer to me.

@kevinushey Were you planning on submitting later to CRAN soon, if so we can coordinate a withr release as well.

**Pull request closed without merging**
