### PR TITLE
WIP: "action" argument

### LINKED ISSUE #2: Use "action" argument instead of "add"
- [ ] with_path
- [ ] with_libpaths
- [ ] with_temp_libpaths (#1)
- [ ] Deprecate with_lib

See https://github.com/hadley/devtools/pull/833/files#r31861098.

### PR DESCRIPTION
**Pull request by krlmlr**
- [x] with_path
- [x] with_libpaths
- [ ] with_temp_libpaths (#1)
- [x] Deprecate with_lib
- [x] with_envvar uses with_something

Fixes #2.

Closes #6.

### CODE REVIEW

**Comment by krlmlr** [comment]
This is ready for a first review. Here the breaking changes:

- `with_lib` is gone
- `set_path` gains an `action` argument but now prepends by default (was: `replace`)
- argument `add` to `with_path` is now called `action`, default: `prefix` (was: `suffix`)

Changing the semantics is very easy due to the enhanced `with_something` function, which is something we should consider documenting and exporting. At some point I might make it super-pretty so that `with_path` reads like this:

```
function (new, code, action = "prepend") 
{
    old <- set_path(new, action = action)
    on.exit(reset_path(old))
    force(code)
}
```

(Now it's `set` instead of `set_path` and `reset` instead of `reset_path`.)

I'd like to decide upon #9 before working on #1.

**Comment by jimhester** [comment]
I actually had an implementation to make the functions look like you describe which I reverted

See the diff of https://github.com/jimhester/withr/commit/6207f183d680e62efec6d83cb8ca798526656593

I went back to the simpler approach because the former seemed hacky for somewhat limited benefit.  It also made the coverage output uglier because there was a temporary file included in the coverage for each invocation of `with_something()`.

If you don't care about fixing the source reference you can simply do 

```r
with_something <- function(set, reset = set) {
  eval(substitute(function(new, code) {
    old <- set(new)
    on.exit(reset(old))
    force(code)
  }, list(set = substitute(set), 
          reset = if (missing(reset)) substitute(set) else substitute(reset))))
}
```
Then
```r
print(with_something(set_path), useSource = FALSE)
# function (new, code)
# {
#     old <- set_path(new)
#     on.exit(set_path(old))
#     force(code)
# }

print(with_something(set_path, reset_path), useSource = FALSE)
# function (new, code)
# {
#     old <- set_path(new)
#     on.exit(reset_path(old))
#     force(code)
# }
```

Only problem with forcibly removing the source reference from the closure (so you don't need `useSource = FALSE` is `covr` needs them to track coverage, but maybe it is worth it...

**Comment by krlmlr** [comment]
Thanks, I'll keep that in mind. Let's stick with the simple approach for now. The coverage report looks ok for this pull request: https://codecov.io/github/jimhester/withr/R?ref=ba85920ef31260be2da671d5df01e0070adb4bd0. Perhaps `bquote` works differently, I'm not really familiar with the internals.

Is this PR good to merge, or are you still reviewing?

**Comment by jimhester** [comment]
Mostly it looks good.  My main comment is about the modified `with_something()`, is the extra complexity necessary?

https://github.com/jimhester/withr/compare/krlmlr-2-action exhibits the same behavior (all tests pass) with a much simpler function.

```r
with_something <- function(set, reset = set, ...) {
  function(new, code, ...) {
    old <- set(new, ...)
    on.exit(reset(old))
    force(code)
  }
}
```

There may be a use-case I am missing, if so let me know, otherwise I would prefer to use the simple definition.

**Comment by krlmlr** [comment]
The behavior is the same, but the interface of the generated function is much nicer in my version ;-)

**Comment by jimhester** [comment]
I think we should either

1. Stick with the simple definition and perform the niceties in the future (interface generation and name substitution)
2. Work on getting the full featured `with_something()` working now.

My suggestion is to do 1. and merge this pull request, then tackle improving `with_something()` in a new PR so we can discuss approaches and what features we want.

**Comment by krlmlr** [comment]
How about

1.5: Have interface generation now, work on parameter substitution later

? The interface is important for generation of documentation (argument detection by Roxygen), name substitution is really a nicety that can wait until later.

**Comment by krlmlr** [comment]
I've merged your simplification for now, but see 196e6788b160 for the resulting documentation changes. Probably Travis will fail as well.

**Pull request merged**
